//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elysee.Infrastruture.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class H3Entities : DbContext
    {
        public H3Entities()
            : base("name=H3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OT_ActivityConfig> OT_ActivityConfig { get; set; }
        public virtual DbSet<OT_Agency> OT_Agency { get; set; }
        public virtual DbSet<OT_AsyncCalling> OT_AsyncCalling { get; set; }
        public virtual DbSet<OT_Attachment> OT_Attachment { get; set; }
        public virtual DbSet<OT_BizAccountCategory> OT_BizAccountCategory { get; set; }
        public virtual DbSet<OT_BizAccountMapping> OT_BizAccountMapping { get; set; }
        public virtual DbSet<OT_BizDbConnectionConfig> OT_BizDbConnectionConfig { get; set; }
        public virtual DbSet<OT_BizListener> OT_BizListener { get; set; }
        public virtual DbSet<OT_BizObjectSchemaDraft> OT_BizObjectSchemaDraft { get; set; }
        public virtual DbSet<OT_BizObjectSchemaPublished> OT_BizObjectSchemaPublished { get; set; }
        public virtual DbSet<OT_BizQuery> OT_BizQuery { get; set; }
        public virtual DbSet<OT_BizQueryItems> OT_BizQueryItems { get; set; }
        public virtual DbSet<OT_BizRule> OT_BizRule { get; set; }
        public virtual DbSet<OT_BizRuleAcl> OT_BizRuleAcl { get; set; }
        public virtual DbSet<OT_BizService> OT_BizService { get; set; }
        public virtual DbSet<OT_BizServiceMethod> OT_BizServiceMethod { get; set; }
        public virtual DbSet<OT_BizServiceSetting> OT_BizServiceSetting { get; set; }
        public virtual DbSet<OT_BizTreeNode> OT_BizTreeNode { get; set; }
        public virtual DbSet<OT_Category> OT_Category { get; set; }
        public virtual DbSet<OT_Comment> OT_Comment { get; set; }
        public virtual DbSet<OT_Company> OT_Company { get; set; }
        public virtual DbSet<OT_Consultancy> OT_Consultancy { get; set; }
        public virtual DbSet<OT_CustomSetting> OT_CustomSetting { get; set; }
        public virtual DbSet<OT_DeletingSPListItem> OT_DeletingSPListItem { get; set; }
        public virtual DbSet<OT_EnumerableMetadata> OT_EnumerableMetadata { get; set; }
        public virtual DbSet<OT_FileServer> OT_FileServer { get; set; }
        public virtual DbSet<OT_FrequentlyUsedComment> OT_FrequentlyUsedComment { get; set; }
        public virtual DbSet<OT_FrequentWorkflow> OT_FrequentWorkflow { get; set; }
        public virtual DbSet<OT_FunctionAcl> OT_FunctionAcl { get; set; }
        public virtual DbSet<OT_FunctionCategory> OT_FunctionCategory { get; set; }
        public virtual DbSet<OT_FunctionDef> OT_FunctionDef { get; set; }
        public virtual DbSet<OT_Group> OT_Group { get; set; }
        public virtual DbSet<OT_GroupChild> OT_GroupChild { get; set; }
        public virtual DbSet<OT_HeapDataItem> OT_HeapDataItem { get; set; }
        public virtual DbSet<OT_InstanceContext> OT_InstanceContext { get; set; }
        public virtual DbSet<OT_InstanceSimulation> OT_InstanceSimulation { get; set; }
        public virtual DbSet<OT_InstanceSimulationDataItem> OT_InstanceSimulationDataItem { get; set; }
        public virtual DbSet<OT_MessageWrapper> OT_MessageWrapper { get; set; }
        public virtual DbSet<OT_OrganizationUnit> OT_OrganizationUnit { get; set; }
        public virtual DbSet<OT_OrgJob> OT_OrgJob { get; set; }
        public virtual DbSet<OT_OrgPost> OT_OrgPost { get; set; }
        public virtual DbSet<OT_OrgPostStaff> OT_OrgPostStaff { get; set; }
        public virtual DbSet<OT_P_Navi> OT_P_Navi { get; set; }
        public virtual DbSet<OT_P_Page> OT_P_Page { get; set; }
        public virtual DbSet<OT_P_PageTemplate> OT_P_PageTemplate { get; set; }
        public virtual DbSet<OT_P_Plugin> OT_P_Plugin { get; set; }
        public virtual DbSet<OT_P_PluginInst> OT_P_PluginInst { get; set; }
        public virtual DbSet<OT_P_PluginInstVal> OT_P_PluginInstVal { get; set; }
        public virtual DbSet<OT_P_PluginPrivateAttr> OT_P_PluginPrivateAttr { get; set; }
        public virtual DbSet<OT_P_PluginPublicAttr> OT_P_PluginPublicAttr { get; set; }
        public virtual DbSet<OT_PageSetting> OT_PageSetting { get; set; }
        public virtual DbSet<OT_PrimitiveMetadata> OT_PrimitiveMetadata { get; set; }
        public virtual DbSet<OT_ScheduleInvoker> OT_ScheduleInvoker { get; set; }
        public virtual DbSet<OT_Segment> OT_Segment { get; set; }
        public virtual DbSet<OT_Signature> OT_Signature { get; set; }
        public virtual DbSet<OT_SpsWorkflowMap> OT_SpsWorkflowMap { get; set; }
        public virtual DbSet<OT_SystemAcl> OT_SystemAcl { get; set; }
        public virtual DbSet<OT_SystemOrgAcl> OT_SystemOrgAcl { get; set; }
        public virtual DbSet<OT_Timer> OT_Timer { get; set; }
        public virtual DbSet<OT_Token> OT_Token { get; set; }
        public virtual DbSet<OT_TreeMetadata> OT_TreeMetadata { get; set; }
        public virtual DbSet<OT_Urgency> OT_Urgency { get; set; }
        public virtual DbSet<OT_User> OT_User { get; set; }
        public virtual DbSet<OT_WorkflowAcl> OT_WorkflowAcl { get; set; }
        public virtual DbSet<OT_WorkflowClause> OT_WorkflowClause { get; set; }
        public virtual DbSet<OT_WorkflowClauseSeqNo> OT_WorkflowClauseSeqNo { get; set; }
        public virtual DbSet<OT_WorkflowFolderAcl> OT_WorkflowFolderAcl { get; set; }
        public virtual DbSet<OT_WorkflowOrgAcl> OT_WorkflowOrgAcl { get; set; }
        public virtual DbSet<OT_WorkflowSheet> OT_WorkflowSheet { get; set; }
        public virtual DbSet<OT_WorkflowTemplateDraft> OT_WorkflowTemplateDraft { get; set; }
        public virtual DbSet<OT_WorkflowTemplatePublished> OT_WorkflowTemplatePublished { get; set; }
        public virtual DbSet<OT_WorkingCalendar> OT_WorkingCalendar { get; set; }
        public virtual DbSet<OT_WorkingDay> OT_WorkingDay { get; set; }
        public virtual DbSet<OT_WorkingTimeSpan> OT_WorkingTimeSpan { get; set; }
        public virtual DbSet<OT_WorkItem> OT_WorkItem { get; set; }
    }
}
