//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elysee.Infrastruture.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_BizQueryItems
    {
        public string ObjectID { get; set; }
        public string PropertyName { get; set; }
        public Nullable<int> IsDisplay { get; set; }
        public Nullable<int> PropertyType { get; set; }
        public Nullable<int> DisplayType { get; set; }
        public Nullable<int> FilterType { get; set; }
        public string SelectedValues { get; set; }
        public string DefaultValue { get; set; }
        public string ParentObjectID { get; set; }
        public string ParentPropertyName { get; set; }
        public Nullable<int> ParentIndex { get; set; }
    }
}
