//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elysee.Infrastruture.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_Comment
    {
        public string ObjectID { get; set; }
        public string BizObjectSchemaCode { get; set; }
        public string BizObjectId { get; set; }
        public string InstanceId { get; set; }
        public string Activity { get; set; }
        public string UserID { get; set; }
        public string OUName { get; set; }
        public Nullable<long> TokenId { get; set; }
        public string DataField { get; set; }
        public string Text { get; set; }
        public Nullable<int> Approval { get; set; }
        public string SignatureId { get; set; }
        public byte[] Signature { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public string ParentObjectID { get; set; }
        public string ParentPropertyName { get; set; }
        public Nullable<int> ParentIndex { get; set; }
    }
}
