//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elysee.Infrastruture.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_FileServer
    {
        public string ObjectID { get; set; }
        public string Code { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
        public Nullable<int> StorageType { get; set; }
        public Nullable<int> DownloadType { get; set; }
        public string DownloadUrl { get; set; }
        public string ServerHost { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string BasePath { get; set; }
        public string DbCode { get; set; }
        public Nullable<int> MaxConcurrency { get; set; }
        public Nullable<int> IsDefault { get; set; }
        public string ParentObjectID { get; set; }
        public string ParentPropertyName { get; set; }
        public Nullable<int> ParentIndex { get; set; }
    }
}
