//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elysee.Infrastruture.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_InstanceContext
    {
        public string ObjectID { get; set; }
        public string SequenceNo { get; set; }
        public Nullable<int> MessageEmergency { get; set; }
        public string InstanceName { get; set; }
        public string Originator { get; set; }
        public string OrgUnit { get; set; }
        public string OriginateGroup { get; set; }
        public string OriginatePost { get; set; }
        public Nullable<int> IsChildInstance { get; set; }
        public string ParentInstanceID { get; set; }
        public string ParentActivityCode { get; set; }
        public Nullable<int> NotifyParentFinished { get; set; }
        public Nullable<int> ParentActivityTokenId { get; set; }
        public byte[] ParentDataMaps { get; set; }
        public string WorkflowCode { get; set; }
        public Nullable<int> WorkflowVersion { get; set; }
        public string BizObjectSchemaCode { get; set; }
        public string BizObjectId { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> InitiativeTokenId { get; set; }
        public Nullable<long> FinalTokenId { get; set; }
        public Nullable<int> NextTokenId { get; set; }
        public Nullable<int> Exceptional { get; set; }
        public Nullable<int> Suspended { get; set; }
        public Nullable<int> UserSuspended { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public Nullable<long> UsedTime { get; set; }
        public Nullable<long> UsedTime_W { get; set; }
        public Nullable<long> UsedTime_C { get; set; }
        public Nullable<long> UsedTime_O { get; set; }
        public Nullable<System.DateTime> PlanFinishTime { get; set; }
        public Nullable<double> UsedTimeRate { get; set; }
        public Nullable<double> Progress { get; set; }
        public Nullable<System.DateTime> EstimatedFinishTime { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Approval { get; set; }
        public string ExternalTableName { get; set; }
        public string ExternalPrimaryKey { get; set; }
        public string ExternalPrimaryValue { get; set; }
        public Nullable<int> SpsBounded { get; set; }
        public string SpsSite { get; set; }
        public string SpsWebName { get; set; }
        public string SpsList { get; set; }
        public Nullable<int> SpsListItemId { get; set; }
        public string SpsListItemUrl { get; set; }
        public Nullable<int> Recurrences { get; set; }
        public Nullable<double> RecurrencesRate { get; set; }
        public Nullable<System.DateTime> LastActiveTime { get; set; }
        public Nullable<int> ArchiveState { get; set; }
        public string ParentObjectID { get; set; }
        public string ParentPropertyName { get; set; }
        public Nullable<int> ParentIndex { get; set; }
    }
}
