//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elysee.Infrastruture.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_PageSetting
    {
        public string ObjectID { get; set; }
        public Nullable<int> SettingType { get; set; }
        public string PageLocalPath { get; set; }
        public string PageRedirectUrl { get; set; }
        public string ControlID { get; set; }
        public Nullable<int> PageSize { get; set; }
        public string ColumnID { get; set; }
        public string ColumnName { get; set; }
        public Nullable<int> ColumnIndex { get; set; }
        public Nullable<int> TextCount { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> WidthType { get; set; }
        public Nullable<int> Visible { get; set; }
        public Nullable<int> HighPrecision { get; set; }
        public Nullable<int> LinkType { get; set; }
        public string ParentObjectID { get; set; }
        public string ParentPropertyName { get; set; }
        public Nullable<int> ParentIndex { get; set; }
    }
}
