//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elysee.Infrastruture.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_SystemOrgAcl
    {
        public string ObjectID { get; set; }
        public string OrgScope { get; set; }
        public Nullable<int> EditOrg { get; set; }
        public Nullable<int> ViewInstance { get; set; }
        public Nullable<int> ViewWorkItem { get; set; }
        public Nullable<int> AdminInstance { get; set; }
        public Nullable<int> AnalyzePerformance { get; set; }
        public Nullable<int> AnalyzeData { get; set; }
        public string UserID { get; set; }
        public Nullable<int> Administrator { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string ParentObjectID { get; set; }
        public string ParentPropertyName { get; set; }
        public Nullable<int> ParentIndex { get; set; }
    }
}
