//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elysee.Infrastruture.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_Token
    {
        public string ObjectID { get; set; }
        public string InstanceId { get; set; }
        public Nullable<int> TokenId { get; set; }
        public string WorkflowCode { get; set; }
        public string Originator { get; set; }
        public string Activity { get; set; }
        public Nullable<int> Approval { get; set; }
        public Nullable<int> SkippedExecution { get; set; }
        public Nullable<int> Exceptional { get; set; }
        public Nullable<int> Retrievable { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string PreTokens { get; set; }
        public Nullable<System.DateTime> FinishedTime { get; set; }
        public Nullable<int> State { get; set; }
        public string Participants { get; set; }
        public Nullable<long> UsedTime { get; set; }
        public Nullable<long> UsedTime_W { get; set; }
        public Nullable<long> UsedTime_C { get; set; }
        public Nullable<long> UsedTime_O { get; set; }
        public Nullable<double> UsedTimeRate { get; set; }
        public string ParentObjectID { get; set; }
        public string ParentPropertyName { get; set; }
        public Nullable<int> ParentIndex { get; set; }
    }
}
