//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elysee.Infrastruture.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_User
    {
        public string ObjectID { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public Nullable<int> ServiceState { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string Appellation { get; set; }
        public string EmployeeNumber { get; set; }
        public Nullable<int> EmployeeLevel { get; set; }
        public string Title { get; set; }
        public string Password { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> IsMobileClientUser { get; set; }
        public Nullable<int> IsConsoleUser { get; set; }
        public string FacsimileTelephoneNumber { get; set; }
        public string IpPhone { get; set; }
        public string HomePhone { get; set; }
        public string OfficePhone { get; set; }
        public string Pager { get; set; }
        public string QQ { get; set; }
        public string RTX { get; set; }
        public string MSN { get; set; }
        public string Skype { get; set; }
        public string Country { get; set; }
        public string CountryName { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string PostOfficeBox { get; set; }
        public string PostalCode { get; set; }
        public string IDNumber { get; set; }
        public string SID { get; set; }
        public Nullable<int> MobileType { get; set; }
        public string DeviceToken { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<int> PrivacyLevel { get; set; }
        public Nullable<int> Notification { get; set; }
        public string ParentID { get; set; }
        public string SourceParentID { get; set; }
        public string CompanyID { get; set; }
        public Nullable<int> Admin { get; set; }
        public string SystemID { get; set; }
        public Nullable<int> Visibility { get; set; }
        public string CategoryID { get; set; }
        public Nullable<int> State { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public string ManagerID { get; set; }
        public string ViceManagerID { get; set; }
        public string SecretaryID { get; set; }
        public string SupervisorID { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public byte[] Attachment { get; set; }
        public Nullable<int> SortKey { get; set; }
        public string WorkflowCode { get; set; }
        public string ParentObjectID { get; set; }
        public string ParentPropertyName { get; set; }
        public Nullable<int> ParentIndex { get; set; }
    }
}
