//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elysee.Infrastruture.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_WorkItem
    {
        public string ObjectID { get; set; }
        public string Participant { get; set; }
        public string OrgUnit { get; set; }
        public string ParticipateGroup { get; set; }
        public string ParticipatePost { get; set; }
        public string Finisher { get; set; }
        public Nullable<int> FinishAccessPoint { get; set; }
        public string WorkflowCode { get; set; }
        public Nullable<int> WorkflowVersion { get; set; }
        public string InstanceId { get; set; }
        public string BizObjectSchemaCode { get; set; }
        public string BizObjectId { get; set; }
        public Nullable<int> TokenId { get; set; }
        public string ActivityCode { get; set; }
        public string ActivityDisplayName { get; set; }
        public string DisplayName { get; set; }
        public string ItemSummary { get; set; }
        public Nullable<int> SheetType { get; set; }
        public string SheetAddress { get; set; }
        public string MobileSheetAddress { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> IsLocking { get; set; }
        public string Locker { get; set; }
        public Nullable<int> IsLocked { get; set; }
        public string CanceledByWorkItem { get; set; }
        public Nullable<System.DateTime> ReceiveTime { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<long> WaitTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public Nullable<System.DateTime> CancelTime { get; set; }
        public Nullable<long> UsedTime { get; set; }
        public Nullable<long> UsedTime_W { get; set; }
        public Nullable<long> UsedTime_C { get; set; }
        public Nullable<long> UsedTime_U { get; set; }
        public Nullable<long> UsedTime_O { get; set; }
        public Nullable<long> PlanUseTime { get; set; }
        public Nullable<int> OvertimePolicy { get; set; }
        public Nullable<System.DateTime> PlanFinishTime { get; set; }
        public string Delegant { get; set; }
        public Nullable<int> Urged { get; set; }
        public Nullable<int> ItemType { get; set; }
        public string SourceWorkItemID { get; set; }
        public string ReturnToWorkItemID { get; set; }
        public string Creator { get; set; }
        public Nullable<int> Consulted { get; set; }
        public Nullable<int> ActivityConsulted { get; set; }
        public Nullable<int> MonitorConsultant { get; set; }
        public Nullable<int> ConsultantFinished { get; set; }
        public Nullable<int> Assisted { get; set; }
        public Nullable<int> ActivityAssisted { get; set; }
        public Nullable<int> MonitorAssistant { get; set; }
        public Nullable<int> AssistantFinished { get; set; }
        public Nullable<long> LongPermittedActions { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Originator { get; set; }
        public Nullable<int> BatchProcessing { get; set; }
        public Nullable<int> EmailNotification { get; set; }
        public Nullable<int> SMSApprove { get; set; }
        public Nullable<int> Approval { get; set; }
        public string ItemComment { get; set; }
        public Nullable<int> MobileProcessing { get; set; }
        public string Receiptor { get; set; }
        public string ItemFlag { get; set; }
        public Nullable<int> ColorArgb { get; set; }
        public string ActionName { get; set; }
        public Nullable<int> PreActionEventType { get; set; }
        public Nullable<int> ActionEventType { get; set; }
        public Nullable<int> ActionButtonType { get; set; }
        public string ParentObjectID { get; set; }
        public string ParentPropertyName { get; set; }
        public Nullable<int> ParentIndex { get; set; }
    }
}
