//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elysee.Infrastruture.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_WorkflowClause
    {
        public string ObjectID { get; set; }
        public Nullable<int> SortKey { get; set; }
        public string DisplayName { get; set; }
        public string WorkflowCode { get; set; }
        public Nullable<int> CurrentNewVersion { get; set; }
        public Nullable<int> DefaultVersion { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> MobileStart { get; set; }
        public string Code { get; set; }
        public Nullable<int> SeqNoResetType { get; set; }
        public string IconContentType { get; set; }
        public byte[] IconContent { get; set; }
        public string CalendarId { get; set; }
        public string ExceptionManager { get; set; }
        public string ParentObjectID { get; set; }
        public string ParentPropertyName { get; set; }
        public Nullable<int> ParentIndex { get; set; }
    }
}
