//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elysee.Infrastruture.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_WorkflowSheet
    {
        public string ObjectID { get; set; }
        public string SheetName { get; set; }
        public string SheetCode { get; set; }
        public byte[] SheetHtml { get; set; }
        public byte[] SheetAspx { get; set; }
        public Nullable<int> SheetType { get; set; }
        public string SheetAddress { get; set; }
        public string LastModifyUser { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
        public string MobileSheetAddress { get; set; }
        public string PrintSheetAddress { get; set; }
        public string ParentObjectID { get; set; }
        public string ParentPropertyName { get; set; }
        public Nullable<int> ParentIndex { get; set; }
    }
}
