//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elysee.Infrastruture.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_WorkflowTemplatePublished
    {
        public string ObjectID { get; set; }
        public string Content { get; set; }
        public string StartActivityCode { get; set; }
        public Nullable<int> WorkflowVersion { get; set; }
        public string Publisher { get; set; }
        public Nullable<System.DateTime> PublishTime { get; set; }
        public Nullable<int> WorkflowState { get; set; }
        public string WorkflowPackageCode { get; set; }
        public string WorkflowCode { get; set; }
        public string BizObjectSchemaCode { get; set; }
        public string ParentObjectID { get; set; }
        public string ParentPropertyName { get; set; }
        public Nullable<int> ParentIndex { get; set; }
    }
}
